name: Automated Release (semantic-release)

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.10.0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: "pnpm"

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Ejecutar semantic-release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
